### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by HeYongRui** [CainKernel/FFmpegAndroid#1]
ffmpeg.c: In function 'sub2video_flush':
ffmpeg.c:302:9: warning: ignoring return value of 'av_buffersrc_add_frame', declared with attribute warn_unused_result [-Wunused-result]
         av_buffersrc_add_frame(ist->filters[i]->filter, NULL);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
AR      libavdevice/libavdevice.a
AR      libavfilter/libavfilter.a
CC      libavformat/os_support.o
In file included from libavformat/os_support.h:112:0,
                 from libavformat/os_support.c:29:
libavformat/os_support.c: In function 'ff_gai_strerror':
libavformat/os_support.c:230:10: error: 'ERROR_NOT_ENOUGH_MEMORY' undeclared (first use in this function)
     case EAI_MEMORY:
          ^
libavformat/os_support.c:230:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [libavformat/os_support.o] Error 1
c:\Users\admin\AppData\Local\Android\sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-ld.exe: cannot find libavcodec/libavcodec.a: No such file or directory
libavfilter/libavfilter.a: member libavfilter/libavfilter.a(aeval.o) in archive is not an object

使用提供的文件(中间根据自己的配置改了sh的一些路径)，也看了博文，改了配置文件，试过很多次，还是编译失败。不知道什么原因。

**Comment by CainKernel** [comment]
我在Readme里面写得很清楚了，建议使用Linux环境编译，我在Ubuntu16.04中已经验证过了的。尽量别用Windows编译，Windows的工具库有不少问题，编译会出现奇奇怪怪的问题。
